name: Jira extract issues
description: Extract issue keys from commit messages
color: blue
icon: git-commit
inputs:
  token:
    description: Your Github token
    required: true
  release-tag:
    description: The release tag, defaults to N-1 release
    required: false
ouputs:
  issue-keys:
    description: All issue keys, separated by a comma
runs:
  using: 'node12'
  main: 'dist/index.js'

